### ISSUE TITLE
Cannot clone Repository, because of quotes in folder name

### ISSUE THREAD

**Issue by seflue** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#45]
Hi,

I tried to clone your project, but it fails:
```
fatal: cannot create directory at 'src/pipelineTestResources/com/mkobit/jenkins/pipelines/IntegrationTestSourceIntegrationTest/"check" lifecycle task executes "integrationTest"': file or directory not found
```

I guess, the quotes in the Spock test name are the cause of this problem.

**Comment by mkobit** [comment]
That is strange, what version of Git are you using? Circle CI clones it OK and I was able

Those directories exists with those names because they are automatically mapped and used in the functional testing.

**Comment by mkobit** [comment]
Closing due to no response.

**Comment by seflue** [comment]
Sorry for the late response:
It seems to be a problem of my git version. I'm using Git 2.7.4 (Ubuntu Xenial) and 2.9.3 (Windows) on my machine at work - on both variants I got the error described. I just tried it on my system at home (2.16.1) and it worked without objection. So indeed, it is a Git version problem.

**Comment by mkobit** [comment]
Thanks for the follow-up
