### ISSUE TITLE
Allow for usage of @Grab in library source

### ISSUE THREAD

**Issue by mkobit** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#46]
https://stackoverflow.com/questions/18173908/error-compiling-a-groovy-project-using-grab-annotation/18174033#18174033

**Comment by daxroc** [comment]
It seems like the better solution for integration, is to add ivy at compile time, this will allow the normal resolution of Grab during the execution.

`
configurations {
    ivy
}

tasks.withType(GroovyCompile) {
    groovyClasspath += configurations.ivy
}

dependencies {
    testImplementation("org.spockframework:spock-core:1.1-groovy-2.4")
    testImplementation("org.assertj:assertj-core:3.9.0")
    ivy group: 'org.apache.ivy', name: 'ivy', version: '2.4.0'
}
`

**Comment by mkobit** [comment]
Thanks @daxroc , that's about how i think we should take it. Definitely need a test to make sure it also works in the timing of unit tests, too.

**Comment by mkobit** [comment]
I've pushed up a couple changes 

Unfortunately, I haven't found a way to make unit testing `@Grab` consuming libraries very easy. I think JenkinsPipelineUnit probably does some transformations on the source where it handles the `@Grab`, but I don't have a test case for that right now. There are apparently some open issues for testing code that uses `@Grab`. 

* https://stackoverflow.com/questions/16471096/any-alternative-to-grabconfig
* https://stackoverflow.com/questions/4611230/no-suitable-classloader-found-for-grab

I think merging it in as-is is probably good enough for most use cases.
