### ISSUE TITLE
Provide an example how to use this plugin without using Kotlin DSL

### ISSUE THREAD

**Issue by kleini** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#59]
I would to stay at first with Groovy DSL in build.gradle files. Can you provide an example how to use your plugin in a build.gradle file?

**Comment by mkobit** [comment]
I think this issue is better suited for https://github.com/mkobit/jenkins-pipeline-shared-library-example - is it alright if I migrate it there?

**Comment by mkobit** [comment]
A few notes that may be helpful
* https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/tree/01762ba70b05b950dff251dcd99811ed1895bdb0/src/pipelineTestResources/projects has all of the different types of samples that the test suite runs against. Some of those may help for what you are looking for
* https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/blob/01762ba70b05b950dff251dcd99811ed1895bdb0/src/pipelineTestResources/projects/gradle-configuration-groovy/build.gradle is a close approximation of how to configure the `build.gradle`, but I can add a more specific setup to the other repository

**Comment by kleini** [comment]
You're right. Migrate it.
Thanks for your hints. I will try to get it working for me and then contribute to your examples.

**Comment by kleini** [comment]
I already got it working. Why did my first try to reference your plugin from my build.gradle file fail? No idea. I thought it was because it was written in Kotlin. The fault sits always in front of the computer!

**Comment by mkobit** [comment]
Issue moved to [mkobit/jenkins-pipeline-shared-library-example #5](https://github.com/mkobit/jenkins-pipeline-shared-library-example/issues/5) via [**ZenHub**](https://www.zenhub.com/)
