### ISSUE TITLE
Is it possible to use this on maven project?

### ISSUE THREAD

**Issue by sleungcy** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#64]
Hi, 

I am using maven for my project, is it possible to use this plugin for a maven project?

Thanks,
Sam

**Comment by mkobit** [comment]
Sorry, this plugin is only built to support Gradle.

**Comment by mkobit** [comment]
The current supported use case is "a shared pipeline library that can be built and tested". Closing, please reach out if you have other questions
