### ISSUE TITLE
Inject custom step handler

### ISSUE THREAD

**Issue by pitkley** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#66]
I'm looking for some way to inject a custom handler for a DSL step in the context of an integration test, similar to what jenkins-pipeline-unit [provides for unit tests with `helper.registerAllowedMethod`](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/8f1a57068561f09a6f76db278ef274e02c6accc9/src/main/groovy/com/lesfurets/jenkins/unit/PipelineTestHelper.groovy#L390-L397).

My use-case is that my step calls the `hipchatSend` step of the [hipchat plugin](https://plugins.jenkins.io/hipchat). For my integration test I don't want to actually send a Hipchat message though, but rather intercept the call and log and verify the parameter-map passed during the invocation.

I currently see two possibilities:

1. Depend on the Hipchat-plugin and use something like [Powermock](https://github.com/powermock/powermock) to replace the [`HipChatSendStepExecution.run`](https://github.com/jenkinsci/hipchat-plugin/blob/27c2b9b27b4e08b78913dc36f6024f5edef4b5a9/src/main/java/jenkins/plugins/hipchat/workflow/HipChatSendStep.java#L134-L217) method to do what I need.
2. Create and implicitly load a dummy shared library that contains a `vars/hipchatSend.groovy` (although I'm not sure how I'd extract parameters supplied to `call` from there).

Does anybody have a hint for me what alternatives there might be, potentially as simple as `helper.registerAllowedMethod`? Thanks!

**Comment by mkobit** [comment]
Quick glance:

- set up a local server in your tests (something like https://github.com/square/okhttp/tree/master/mockwebserver or http://www.mock-server.com/mock_server/running_mock_server.html )
- (Maybe) preconfigure the [`HipChatNotifier.DescriptorImpl` global `server` field to your local test endpoint](https://github.com/jenkinsci/hipchat-plugin/blob/27c2b9b27b4e08b78913dc36f6024f5edef4b5a9/src/main/java/jenkins/plugins/hipchat/HipChatNotifier.java#L412)
- (Maybe) Change the `server` parameter of [`hipchatSend`](https://jenkins.io/doc/pipeline/steps/hipchat/#hipchatsend-send-hipchat-message) to the local endpoint
- verify any of the data you want from the server

That is a bit of work but is close to realistic testing. There are probably othe roptions but this is the first that came to my mind.

**Comment by pitkley** [comment]
Thanks for your input. I was thinking about mocking the HTTP-server, and have now successfully done this.

For the general question: if I undestand you correctly, there is currently no "best-practice" mechanism in place for replacing/adding a Jenkins step during an integration test, yes?

No matter the answer, you have already helped me for this specific case and the issue can be closed from my side, if there isn't anything further you'd like to track here. 👍

**Comment by mkobit** [comment]
There might be a way using `@TestExtension` and `@Symbol` to "override" the step, but might be error prone. I think the _JenkinsPipelineUnit_ for mocking/verifying calls is a good approach at a low level, and then intercepting the actual HTTP calls with some mock-server-like implementation is a good approach when you want to test closer to the actual steps implementation. One thing to be careful of is to now conflict with Jenkins' dependencies, as it can get very unhappy if you resolve to a different version than Jenkins is built with.

Thanks for the follow up, closing.
