### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by mkobit** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#7]

**Comment by mkobit** [comment]
Gradle 4.3-rc-1 (kotlin-dsl 0.12.0) will run on Java 9, so no blockers

**Comment by mkobit** [comment]
well, actually Jenkins has some problems so going to wait a bit

https://issues.jenkins-ci.org/browse/JENKINS-40689

**Comment by mkobit** [comment]
https://jenkins.io/blog/2019/03/11/let-s-celebrate-java-11-support/

Java 11 support added in Jenkins `2.164` - this project should still be built on Java 8 but tested against Java 11 and multiple Jenkins versions

**Comment by muhlba91** [comment]
Is there any progress on this issue?

**Comment by mkobit** [comment]
@muhlba91 I haven't started it, but I will try to pick it up soon.

I think a short-term workaround for users who want to use Java 11 would be to add a dependency on the library that contains the `@Generated`

```
implementtaion("javax.annotation:javax.annotation-api:1.3.2")
```

I think I might remove the `@Generated` annotation that is put on the generated code to simplify it.
