### ISSUE TITLE
Handle Gradle 4.10 and kotlin-dsl 1.0-rc

### ISSUE THREAD

**Issue by mkobit** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#70]
This will probably cause breakages and bump the minimum Gradle version up to 4.10

**Comment by mstrangfeld** [comment]
#72 
Works but as you said it will bump the minimum Gradle version up to 4.10

**Comment by mkobit** [comment]
Thanks @mstrangfeld ! I'll try to take a look at it later today.

**Comment by mkobit** [comment]
created https://github.com/mkobit/jenkins-pipeline-shared-libraries-gradle-plugin/issues/74 to figure out why builds failing on CI, but going to close this. after I resolve CI issues I think I'll release the next version
