### ISSUE TITLE
currentBuild exists in real jenkins but not when run through plugin

### ISSUE THREAD

**Issue by rvodden** [mkobit/jenkins-pipeline-shared-libraries-gradle-plugin#71]
I have a really strange error - I have uploaded an example repo which replicates the issue as succinctly and completely as I can. What appears to be happening is that `currentBuild` is not defined in a global method in the test harness, but it is in a real jenkins...

I have the following `vars/testEcho.groovy`
```groovy
def call() {
    this.echo this.currentBuild.displayName
}
```

A `Jenkinsfile` thus:
```groovy
testLibrary = libraryFromLocalRepo()

echo currentBuild.toString()

pipeline {
    agent any
    stages {
        stage ('Test Echo') {
            steps {
                script {
                    try {
                        testEcho()
                    } catch (Exception exception) {
                        echo exception.toString()
                        throw exception
                    }
                }
            }
        }
    }
}


def libraryFromLocalRepo() {
    // Workaround for loading the current repo as shared build lib.
    // Checks out to workspace local folder named like the identifier.
    // We have to pass an identifier with version (which is ignored). Otherwise the build fails.
    library(identifier: 'local-library@snapshot', retriever: legacySCM(scm))
}
```
And a `TestLibrarySpecification.groovy` thus:
```groovy
def "testLibrary is used in a job"() {
        given: "a job contains a call to a library which uses a global variable"
        WorkflowJob workflowJob = jenkinsRule.createProject(WorkflowJob, 'project')

        workflowJob.definition = new CpsFlowDefinition("""
            @Library('testLibrary') _
            
            echo this.currentBuild.toString()

            pipeline {
                agent any
                stages {
                    stage ('Test Echo') {
                        steps {
                            script {
                                try {
                                    testEcho()
                                } catch (Exception exception) {
                                    echo exception.toString()
                                    throw exception
                                }
                            }
                        }
                    }
                }
            }
        """.stripIndent(), true)

        when: "the job is run"
        QueueTaskFuture queueTaskFuture = new ParameterizedJobMixIn() {
            @Override protected Job asJob() {
                return workflowJob;
            }
        }.scheduleBuild2(0);

        then: "the build should run successfully"
        WorkflowRun result = jenkinsRule.assertBuildStatusSuccess(queueTaskFuture)
    }
```
The test log for the build (which fails) is here:
https://gist.github.com/rvodden/288733624a7b07bb891538e03dbab71d
The important bit is:
```
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Test Echo)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
groovy.lang.MissingPropertyException: No such property: currentBuild for class: testEcho
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

and the Jenkins log for the build which succeeds is here:
https://gist.github.com/rvodden/589f68a3c29462433843f417f93c8b61
The important bit is:
```
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test Echo)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
#4
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
The only difference I can obviously see is how the library is loaded, but that seems to have no effect at all on the construction of the build. Any help would be greatly appreciated.

**Comment by mkobit** [comment]
Would you be able upload or share the dependencies of the build? Either by sharing the `sharedLibrary` part of your build script, a Gradle build scan, or output of `./gradlew dependencies`?

At first glance everything looks right from your side, so maybe it is a version difference between the plugins?

**Comment by rvodden** [comment]
Sorry! I actually created a repo to isolate the 'bug' and forgot to put the link in the issue! 

https://github.com/rvodden/bug-replication

**Comment by mkobit** [comment]
Ok so I noticed that commenting out

```groovy
    integrationTestCompile sourceSets.main.output
```

to

```groovy
    //integrationTestCompile sourceSets.main.output
```

so that the main classes are not on the Jenkins runtime classpath _seems_ to resolve it. I don't know if Jenkins chokes when it is trying to compile the library but classes with those names already exist on the Jenkins classpath. Maybe [JENKINS-44079](https://issues.jenkins-ci.org/browse/JENKINS-44079) is related? I'm not sure about the best way to handle this.

**Comment by rvodden** [comment]
Thank you so much! That has fixed it for both the 'bug replication' repo and my main repository in which I was experiencing the bug. That line doesn't seem to have any effect either - I imagine I put it there to persuade IntelliJ to find something it couldn't, but now it seems to be able to find it. One to add to the experience list. I really appreciate the time you spent on this.
